version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: biro-back
      POSTGRES_PASSWORD: biro-back
      POSTGRES_DB: biro-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
